[package]
name = "agsol-gold-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
agsol-gold-contract = { path = "../contract", features = ["client"] }
agsol-common = "0.0.1"
agsol-wasm-client = { version = "0.0.1", features = ["wasm-factory"] }
anyhow = "1"
borsh = "0.9.0"
js-sys = "0.3"
metaplex-token-metadata = { git = "https://github.com/zgendao/metaplex", branch = "experiments", features = ["no-entrypoint"] }
serde_json = "1.0"
spl-token = { git = "https://github.com/zgendao/solana-program-library.git", features = ["no-entrypoint"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[dev-dependencies]
agsol-common = "0.1.0"
env_logger = "0.9.0"
log = "0.4"
solana-client = "1.9.0"
solana-sdk = "1.9.0"
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
