version: "3.7"
services:
  gold-rust:
    image: zgendao/gold-rust:main
    restart: unless-stopped
    volumes:
      - ./bot.json:/bot.json:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=gold-stack"

  watchtower:
     image: containrrr/watchtower:latest
     restart: unless-stopped
     command: --scope gold-stack --cleanup --interval 30 --stop-timeout 30s
     environment:
       - REPO_USER=
       - REPO_PASS=
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - /var/run/docker.sock:/var/run/docker.sock:rw
